session: camillaconforti

root: ~/works/camillaconforti/

windows:
  - name: code 
    commands: 
    - nvim 
  - name: dev
    commands: 
    - npm start
  - name: git
    commands: 
    - git status 
