session: rabbitmq-client

root: ~/works/rabbitmq-stream-js-client/

windows:
  - name: code 
    commands: 
    - nvim 
  - name: dev
    commands: 
    - docker-compose up -d
  - name: git
    commands: 
    - git status 
