session: uhubs-backend

root: /home/lg/Works/uhubs-backend/

windows:
  - name: code 
    commands: 
    - nvim 
  - name: dev
    commands: 
    - direnv reload && npm run watch-debug
  - name: git
    commands: 
    - git status 
  - name: cloud_db
    commands: 
    - ~/cloud_sql_proxy -instances=zeta-envoy-291317:europe-west1:database-dev=tcp:2345
  - name: local_db
    commands: 
    - docker-compose up -d && psql "host=127.0.0.1 port=5434 sslmode=disable dbname=uhubs-dev user=postgres"
