session: uhubs-frontend

root: /home/lg/Works/uhubs-frontend/

windows:
  - name: code 
    commands: 
    - nvim 
  - name: dev
    commands: 
    - npm run dev
  - name: git
    commands: 
    - git status 
