[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "Hack Nerd Font Mono"

[window]
opacity = 0.95

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 10
y = 10
